# -*- coding: utf-8 -*-
"""MCQ Program.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CeHFtEX09YFfWhNV4XR21slfhfr8Qcfd
"""

import json

# Opening JSON file
f = open('quiz-data.json')

data = json.load(f)
f.close()

data

def load_questions(data):
    return data

def quiz(questions):
    ready_to_play = input("Are you ready to play? (Yes/No): ").lower()

    if ready_to_play == 'yes':
        score = 0
        total_questions = len(questions)

        for i, question in enumerate(questions, 1):
            print(f"\nQuestion {i}: {question['question']}")
            for j, choice in enumerate(question['choices'], 1):
                print(f"{j}. {choice}")

            user_answer = input("Your answer (1, 2, 3, 4): ")
            correct_answer = question['correct_ans']

            if user_answer == correct_answer:
                print("Correct!")
                score += 1
            else:
                print(f"Wrong! The correct answer is {correct_answer}.")

        print(f"\nYour final score is {score}/{total_questions}")
    else:
        print("Play Again Whenever You're Ready!")

quiz(data)

